library(caret)
set.seed(123)
V1 = as.integer(readline(prompt = "Enter the size of the tumor (V1):"))
V2 = as.integer(readline(prompt = "Enter the size of the tumor (V2):"))
V3 = as.integer(readline(prompt = "Enter the size of the tumor (V3):"))
test = data.frame(V1=V1,V2=V2,V3=V3)
biopsy_model <- glm(class ~ V1 + V2 + V3,data = biopsy, family = "binomial")
pred <- predict(biopsy_model, newdata = test, type = "response")
res = ifelse(pred > 0.5,"malignant","benign")
cat("The tumor is ",res,"\n")